<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblMenuMasterSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tblmenumaster')->insert([
       [
			"id"=> 63,
			"menu_name"=> "Workforce Planning",
			"parent_id"=> 48,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 130,
			"menu_name"=> "WhatsApp Report",
			"parent_id"=> 117,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 144,
			"menu_name"=> "User Payroll History",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 13,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 8,
			"menu_name"=> "User Management",
			"parent_id"=> 1,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-account-group",
			"status"=> 1,			
            "sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		],
         [
			"id"=> 101,
			"menu_name"=> "User Attendannce",
			"parent_id"=> 93,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 93,
			"menu_name"=> "User Attendance",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 152,
			"menu_name"=> "Trend Analysis",
			"parent_id"=> 125,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 84,
			"menu_name"=> "Training Programs",
			"parent_id"=> 76,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 61,
			"menu_name"=> "Training & Orientation",
			"parent_id"=> 47,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 76,
			"menu_name"=> "Training & Development",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 10,
			"menu_name"=> "Template Management",
			"parent_id"=> 1,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-note-multiple",
			"status"=> 1,			
            "sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
        ],
         [
			"id"=> 32,
			"menu_name"=> "Template Management",
			"parent_id"=> 10,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 18,
			"menu_name"=> "Task management (Activity Stream)",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 51,
			"menu_name"=> "Talent Pool Management",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 64,
			"menu_name"=> "Talent Mobility & Succession Planning",
			"parent_id"=> 48,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 3,
			"menu_name"=> "Talent Management",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 19,
			"menu_name"=> "Suggestion to organization",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 8,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 20,
			"menu_name"=> "Suggestion to for department & Department head",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 9,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 21,
			"menu_name"=> "Suggestion for employee",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 48,
			"menu_name"=> "Succession Planning & Performance Management",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 24,
			"menu_name"=> "Skills",
			"parent_id"=> 8,
			"level"=> 3,
			"page_type"=> "link",
			"access_link"=> "https://form-scholar-clone.vercel.app/submit/9b13d496-362e-45b4-b9f8-de0867b94521",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 54,
			"menu_name"=> "Skill-Based Job Descriptions",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 67,
			"menu_name"=> "Skill-Based Evaluations",
			"parent_id"=> 49,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 39,
			"menu_name"=> "Skill Taxonomy Creation",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 40,
			"menu_name"=> "Skill Ontology Creation",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 41,
			"menu_name"=> "Skill Matrix ",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 43,
			"menu_name"=> "Skill Mapping",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 2,
			"menu_name"=> "Skill Management",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 37,
			"menu_name"=> "Skill Library",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "page",
			"access_link"=> "Libraries/skillLibrary.tsx",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 26,
			"menu_name"=> "Skill Gap Analysis",
			"parent_id"=> 8,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 68,
			"menu_name"=> "Skill Gap Analysis",
			"parent_id"=> 50,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 42,
			"menu_name"=> "Skill Framework",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 62,
			"menu_name"=> "Skill Development Roadmap",
			"parent_id"=> 47,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 34,
			"menu_name"=> "Skill Database & Repository",
			"parent_id"=> 2,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-alpha-s-circle",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 151,
			"menu_name"=> "Skill Dashboards",
			"parent_id"=> 125,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 78,
			"menu_name"=> "Skill Assessment",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 50,
			"menu_name"=> "Skill  Gap & Analysis",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 31,
			"menu_name"=> "Send WhatsApp User",
			"parent_id"=> 9,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 27,
			"menu_name"=> "Send SMS to User",
			"parent_id"=> 9,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 127,
			"menu_name"=> "Send SMS Report",
			"parent_id"=> 117,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 28,
			"menu_name"=> "Send Notification User",
			"parent_id"=> 9,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 29,
			"menu_name"=> "Send Email User",
			"parent_id"=> 9,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 30,
			"menu_name"=> "Send Email Other User",
			"parent_id"=> 9,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 86,
			"menu_name"=> "Self-Assessment",
			"parent_id"=> 77,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 88,
			"menu_name"=> "Self skill rating",
			"parent_id"=> 78,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 87,
			"menu_name"=> "Search skill",
			"parent_id"=> 78,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 17,
			"menu_name"=> "Search Employees by Skills",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 139,
			"menu_name"=> "Salary Structure Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 8,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 106,
			"menu_name"=> "Salary Structure",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 110,
			"menu_name"=> "Salary Certificate",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 107,
			"menu_name"=> "Rollover Salary Structure",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 45,
			"menu_name"=> "Role-based competency frameworks.",
			"parent_id"=> 36,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 70,
			"menu_name"=> "Role Insights",
			"parent_id"=> 50,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 56,
			"menu_name"=> "Resume Screening",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 81,
			"menu_name"=> "Reskilling & Upskilling Opportunities",
			"parent_id"=> 75,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 75,
			"menu_name"=> "Reskilling & Upskilling",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 6,
			"menu_name"=> "Reports",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 128,
			"menu_name"=> "Register User Report",
			"parent_id"=> 117,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 46,
			"menu_name"=> "Recruitment & Hiring",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 22,
			"menu_name"=> "Profile",
			"parent_id"=> 8,
			"level"=> 3,
			"page_type"=> "blade",
			"access_link"=> "user/add_user",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 58,
			"menu_name"=> "Pre-Assessment Tools",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 49,
			"menu_name"=> "Performance Reviews & Appraisals",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 44,
			"menu_name"=> "Peer-to-peer skill endorsements and project-based skill tracking.",
			"parent_id"=> 35,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 142,
			"menu_name"=> "Payroll Type Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 11,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 105,
			"menu_name"=> "Payroll Type",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 141,
			"menu_name"=> "Payroll Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 10,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 95,
			"menu_name"=> "Payroll Management",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 108,
			"menu_name"=> "Payroll Deduction",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 1,
			"menu_name"=> "Organizational Management",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-domain",
			"status"=> 1,
            "sort_order"=> 1,
			"sub_institute_id"=> "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
        ],
          [
			"id"=> 13,
			"menu_name"=> "Organization Structure",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "page",
			"access_link"=> "org_stracture",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 98,
			"menu_name"=> "Organization Handbook",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 7,
			"menu_name"=> "Organization Details",
			"parent_id"=> 1,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-domain",
			"status"=> 1,
            "sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
            "menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		], [
			"id"=> 129,
			"menu_name"=> "Notification Report",
			"parent_id"=> 117,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 60,
			"menu_name"=> "New Hire Documentation",
			"parent_id"=> 47,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 133,
			"menu_name"=> "New Attendance Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 104,
			"menu_name"=> "My Leave",
			"parent_id"=> 94,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 100,
			"menu_name"=> "My Attendance",
			"parent_id"=> 93,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 140,
			"menu_name"=> "Monthly Payroll Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 9,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 145,
			"menu_name"=> "Monthly Attendance Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 14,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 85,
			"menu_name"=> "Mentorship & Coaching",
			"parent_id"=> 76,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 113,
			"menu_name"=> "Manage Handbook",
			"parent_id"=> 98,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 112,
			"menu_name"=> "Manage Document",
			"parent_id"=> 97,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 121,
			"menu_name"=> "Log Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 147,
			"menu_name"=> "Log Report",
			"parent_id"=> 121,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 4,
			"menu_name"=> "LMS",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 137,
			"menu_name"=> "Leave Summery Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 136,
			"menu_name"=> "Leave Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 94,
			"menu_name"=> "Leave management",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 138,
			"menu_name"=> "Leave Encashment",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 103,
			"menu_name"=> "Leave Authorisation",
			"parent_id"=> 94,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 83,
			"menu_name"=> "Learning Path Recommendations",
			"parent_id"=> 75,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 65,
			"menu_name"=> "KRA & KPI Library",
			"parent_id"=> 48,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 91,
			"menu_name"=> "Knowing Yourself",
			"parent_id"=> 79,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 38,
			"menu_name"=> "JobRole Library",
			"parent_id"=> 34,
			"level"=> 3,
			"page_type"=> "page",
			"access_link"=> "Libraries/JobroleLibrary.tsx",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
            'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 53,
			"menu_name"=> "Job Posting & Tracking",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 90,
			"menu_name"=> "Intrest Profiler",
			"parent_id"=> 79,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 57,
			"menu_name"=> "Interview Management",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 73,
			"menu_name"=> "Internal role & project suggestions",
			"parent_id"=> 52,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 71,
			"menu_name"=> "Internal & External Talent Database",
			"parent_id"=> 51,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 16,
			"menu_name"=> "Individual right management",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 119,
			"menu_name"=> "HRMS Reports",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 5,
			"menu_name"=> "HRIT Solutions",
			"parent_id"=> 0,
			"level"=> 1,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 15,
			"menu_name"=> "Group wise right management",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 69,
			"menu_name"=> "Goal Setting",
			"parent_id"=> 50,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 124,
			"menu_name"=> "Frontdesk Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 8,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 150,
			"menu_name"=> "Frontdesk Report",
			"parent_id"=> 124,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 99,
			"menu_name"=> "Front Desk Operations",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 114,
			"menu_name"=> "Front Desk",
			"parent_id"=> 99,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 109,
			"menu_name"=> "Form 16",
			"parent_id"=> 95,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 47,
			"menu_name"=> "Employee Onboarding",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 122,
			"menu_name"=> "Employee Info Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 148,
			"menu_name"=> "Employee Info Report",
			"parent_id"=> 122,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 126,
			"menu_name"=> "Email Report",
			"parent_id"=> 117,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 134,
			"menu_name"=> "Early Going Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 120,
			"menu_name"=> "Document Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 146,
			"menu_name"=> "Document Report",
			"parent_id"=> 120,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 97,
			"menu_name"=> "Document Management System",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 135,
			"menu_name"=> "Dept.wise Attendance Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 115,
			"menu_name"=> "Deceplinry management",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 116,
			"menu_name"=> "Deceplinary action and their management",
			"parent_id"=> 115,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 153,
			"menu_name"=> "Custom Reports",
			"parent_id"=> 125,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 74,
			"menu_name"=> "Course/Content Library,Teach/Learn",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "blade",
			"access_link"=> "lms/add_course",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 123,
			"menu_name"=> "Counselling Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 149,
			"menu_name"=> "Counselling Report",
			"parent_id"=> 123,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 96,
			"menu_name"=> "Compliance Management",
			"parent_id"=> 5,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 131,
			"menu_name"=> "Complaint Report",
			"parent_id"=> 118,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 11,
			"menu_name"=> "Complaint Mgmt",
			"parent_id"=> 1,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-message-bulleted",
			"status"=> 1,		
            "sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
        ],[
			"id"=> 33,
			"menu_name"=> "Complaint Mgmt",
			"parent_id"=> 11,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 118,
			"menu_name"=> "Complaint ",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 111,
			"menu_name"=> "Complaince library",
			"parent_id"=> 96,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 36,
			"menu_name"=> "Competeancy management",
			"parent_id"=> 2,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 9,
			"menu_name"=> "Communication Tools",
			"parent_id"=> 1,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "mdi mdi-account-voice",
			"status"=> 1,			
            "sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		],[
			"id"=> 117,
			"menu_name"=> "Communication Report",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 35,
			"menu_name"=> "Collaboration Tools:",
			"parent_id"=> 2,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 25,
			"menu_name"=> "Certifications",
			"parent_id"=> 8,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 5,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 52,
			"menu_name"=> "Career Matches",
			"parent_id"=> 3,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 79,
			"menu_name"=> "Career Explorer",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 6,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 92,
			"menu_name"=> "Career Explorer",
			"parent_id"=> 79,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 82,
			"menu_name"=> "Career Counseling & Path Guidance",
			"parent_id"=> 75,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 89,
			"menu_name"=> "Career Awareness",
			"parent_id"=> 79,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 55,
			"menu_name"=> "Candidate Skill Assessment & Matching",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 143,
			"menu_name"=> "Bankwise Payroll Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 12,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 132,
			"menu_name"=> "Attendance Report",
			"parent_id"=> 119,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 59,
			"menu_name"=> "ATS Integration",
			"parent_id"=> 46,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 7,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 23,
			"menu_name"=> "Assigned task",
			"parent_id"=> 8,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 77,
			"menu_name"=> "Assesment library",
			"parent_id"=> 4,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 66,
			"menu_name"=> "Appraisals & Feedback",
			"parent_id"=> 48,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 4,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 102,
			"menu_name"=> "Apply Leave",
			"parent_id"=> 94,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
	 ],
        [
			"id"=> 125,
			"menu_name"=> "Analytics and Reporting",
			"parent_id"=> 6,
			"level"=> 2,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 9,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 80,
			"menu_name"=> "All Courses, Multi-source learning materials",
			"parent_id"=> 74,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 72,
			"menu_name"=> "AI-Based Recommendations",
			"parent_id"=> 51,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 2,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
		 ],
        [
			"id"=> 14,
			"menu_name"=> "Admin and Configuration Module",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "",
			"access_link"=> "",
			"icon"=> "",
			"status"=> 1,
			"sort_order"=> 3,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
        ],
        [
			"id"=> 12,
			"menu_name"=> "Add Organization Detail",
			"parent_id"=> 7,
			"level"=> 3,
			"page_type"=> "link",
			"access_link"=> "https://erp.triz.co.in",
			"icon"=> "mdi mdi-domain",
			"status"=> 1,		
            "sort_order"=> 1,
			"sub_institute_id" => "1,2,3",
			"menu_type"=> "",
              'deleted_at'=>null,
            'created_at' => now(),
            'updated_at' => null,
        ]
    ]);

    }
}
