<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TblUserSeeder extends Seeder
{
    public function run(): void
    {
        // Get reference IDs
        $userProfileId = DB::table('tbluserprofilemaster')->value('id');
        $clientId = DB::table('tblclient')->value('id');
        $subInstituteId = DB::table('school_setup')->value('id');

        DB::table('tbluser')->insert([
            [
                'user_name' => 'adminuser',
                'password' => Hash::make('admin'),
                'plain_password' => 'admin',
                'name_suffix' => 'Mr.',
                'first_name' => 'Admin',
                'middle_name' => 'System',
                'last_name' => 'User',
                'email' => 'kalpesh@triz.co.in',
                'mobile' => '9876543210',
                'gender' => 'M',
                'birthdate' => '1990-01-01',
                'address' => '123 Admin Street',
                'city' => 'AdminCity',
                'state' => 'AdminState',
                'pincode' => '123456',
                'otp' => null,
                'user_profile_id' => $userProfileId,
                'join_year' => '2020',
                'image' => null,
                'sub_institute_id' => $subInstituteId,
                'client_id' => $clientId,
                'is_admin' => false,
                'portal_user' => false,
                'status' => true,
                'last_login' => null,
                'login_ip' => '127.0.0.1',
                'landmark' => 'Near Main Office',
                'address_2' => null,
                'expire_date' => null,
                'total_lecture' => 30,
                'subject_ids' => '1,2,3',
                'allocated_standards' => 'A,B,C',
                'bank_name' => 'Test Bank',
                'branch_name' => 'Main Branch',
                'amount' => 50000.00,
                'transfer_type' => 'NEFT',
                'account_no' => '1234567890',
                'ifsc_code' => 'TEST0001234',
                'jobtitle_id' => null,
                'department_id' => null,
                'employee_no' => 'EMP001',
                'qualification' => 'M.Sc.',
                'occupation' => 'Teacher',
                'pan_no' => 'ABCDE1234F',
                'aadhar_no' => '123412341234',
                'pf_no' => 'PF123456',
                'esic_no' => 'ESIC123456',
                'uan_no' => 'UAN123456',
                'tds_deduction' => true,
                'pf_deduction' => true,
                'pt_deduction' => true,
                'joined_date' => '2020-06-01',
                'probation_period_from' => '2020-06-01',
                'probation_period_to' => '2020-12-01',
                'terminated_date' => null,
                'termination_reason' => null,
                'notice_fromdate' => null,
                'notice_todate' => null,
                'noticereason' => null,
                'openingleave' => 10,
                'relieving_date' => null,
                'relieving_reason' => null,
                'CL_opening_leave' => 5,
                'supervisor_opt' => null,
                'employee_id' => null,
                'load' => 6,
                'reporting_method' => 'Email',
                'monday' => true,
                'tuesday' => true,
                'wednesday' => true,
                'thursday' => true,
                'friday' => true,
                'saturday' => false,
                'sunday' => false,
                'monday_in_date' => null,
                'monday_out_date' => null,
                'tuesday_in_date' => null,
                'tuesday_out_date' => null,
                'wednesday_in_date' => null,
                'wednesday_out_date' => null,
                'thursday_in_date' => null,
                'thursday_out_date' => null,
                'friday_in_date' => null,
                'friday_out_date' => null,
                'saturday_in_date' => null,
                'saturday_out_date' => null,
                'sunday_in_date' => null,
                'sunday_out_date' => null,
                'total_experience' => 5,
                'employee_deposite' => 10000.00,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
            ],
            [
                'user_name' => 'employeeUser',
                'password' => Hash::make('staff'),
                'plain_password' => 'staff',
                'name_suffix' => 'Mr.',
                'first_name' => 'Employee',
                'middle_name' => 'System',
                'last_name' => 'User',
                'email' => 'employee@triz.co.in',
                'mobile' => '9876543210',
                'gender' => 'M',
                'birthdate' => '1990-01-01',
                'address' => '123 Admin Street',
                'city' => 'AdminCity',
                'state' => 'AdminState',
                'pincode' => '123456',
                'otp' => null,
                'user_profile_id' => $userProfileId,
                'join_year' => '2020',
                'image' => null,
                'sub_institute_id' => $subInstituteId,
                'client_id' => $clientId,
                'is_admin' => false,
                'portal_user' => false,
                'status' => true,
                'last_login' => null,
                'login_ip' => '127.0.0.1',
                'landmark' => 'Near Main Office',
                'address_2' => null,
                'expire_date' => null,
                'total_lecture' => 30,
                'subject_ids' => '1,2,3',
                'allocated_standards' => 'A,B,C',
                'bank_name' => 'Test Bank',
                'branch_name' => 'Main Branch',
                'amount' => 50000.00,
                'transfer_type' => 'NEFT',
                'account_no' => '1234567890',
                'ifsc_code' => 'TEST0001234',
                'jobtitle_id' => null,
                'department_id' => null,
                'employee_no' => 'EMP001',
                'qualification' => 'M.Sc.',
                'occupation' => 'Teacher',
                'pan_no' => 'ABCDE1234F',
                'aadhar_no' => '123412341234',
                'pf_no' => 'PF123456',
                'esic_no' => 'ESIC123456',
                'uan_no' => 'UAN123456',
                'tds_deduction' => true,
                'pf_deduction' => true,
                'pt_deduction' => true,
                'joined_date' => '2020-06-01',
                'probation_period_from' => '2020-06-01',
                'probation_period_to' => '2020-12-01',
                'terminated_date' => null,
                'termination_reason' => null,
                'notice_fromdate' => null,
                'notice_todate' => null,
                'noticereason' => null,
                'openingleave' => 10,
                'relieving_date' => null,
                'relieving_reason' => null,
                'CL_opening_leave' => 5,
                'supervisor_opt' => null,
                'employee_id' => null,
                'load' => 6,
                'reporting_method' => 'Email',
                'monday' => true,
                'tuesday' => true,
                'wednesday' => true,
                'thursday' => true,
                'friday' => true,
                'saturday' => false,
                'sunday' => false,
                'monday_in_date' => null,
                'monday_out_date' => null,
                'tuesday_in_date' => null,
                'tuesday_out_date' => null,
                'wednesday_in_date' => null,
                'wednesday_out_date' => null,
                'thursday_in_date' => null,
                'thursday_out_date' => null,
                'friday_in_date' => null,
                'friday_out_date' => null,
                'saturday_in_date' => null,
                'saturday_out_date' => null,
                'sunday_in_date' => null,
                'sunday_out_date' => null,
                'total_experience' => 5,
                'employee_deposite' => 10000.00,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now(),
            ],
        ]);
    }
}
