<?php
/**
 * Generate the reversal for 2026_09_21_120000_give_employees_the_leave_menu.
 *
 *   php Docs/hrit-audit/_evidence/gen-reversal-nav.php
 *
 * GENERATED, NOT WRITTEN. The Q8 reversal was hand-authored and every JSON
 * payload in it was wrong - invented structures that did not match the rows it
 * claimed to restore. A reversal nobody can run is worse than none, because it
 * reads as a safety net. So this one is emitted from the before-image captured
 * before the migration ran, and the two hosts get separate sections because
 * their employee rights genuinely differ (82 rows on 202.47.117.220, 41 on
 * 128.199.17.97 - these tables are NOT the byte-identical pair the payroll
 * tables are).
 */
$src = __DIR__ . '/before-nav-employee.json';
if (!is_file($src)) {
    fwrite(STDERR, "missing before-image: $src\n");
    exit(1);
}

$before = json_decode(file_get_contents($src), true);

// Every menu the migration adds or removes. The reversal must return exactly
// these to what they were and touch nothing else.
$touched = [
    94, 103,                                                     // GRANT
    95, 105, 106, 107, 108, 109, 110, 140, 307, 308, 310, 311,   // REVOKE
    101, 162, 163, 164, 102, 104, 165, 166, 167,
];

$hosts = ['mysql' => '202.47.117.220 (web.triz.co.in)', 'live' => '128.199.17.97 (lms.triz.co.in)'];

$out = [];
$out[] = '-- REVERSAL - 2026-09-21 - employee HRIT menu rights (F-209)';
$out[] = '--';
$out[] = '-- Reverses database/migrations/2026_09_21_120000_give_employees_the_leave_menu.php';
$out[] = '-- GENERATED by Docs/hrit-audit/_evidence/gen-reversal-nav.php from';
$out[] = '-- Docs/hrit-audit/_evidence/before-nav-employee.json, captured before the';
$out[] = '-- migration ran. Do not hand-edit: regenerate.';
$out[] = '--';
$out[] = '-- Prefer:  php artisan migrate:rollback --step=1';
$out[] = '--          php artisan migrate:rollback --database=live --step=1';
$out[] = '-- This file is the exact-fidelity restore for when that is not available,';
$out[] = '-- or when the prior state must be proven row by row.';
$out[] = '';

foreach ($hosts as $conn => $label) {
    if (!isset($before[$conn])) {
        $out[] = "-- ($conn was unreachable when the before-image was captured; no section emitted)";
        $out[] = '';
        continue;
    }

    $profileIds = array_map(fn ($p) => (int) $p['id'], $before[$conn]['profiles']);
    $rows = array_values(array_filter(
        $before[$conn]['rights'],
        fn ($r) => in_array((int) $r['menu_id'], $touched, true)
    ));

    $out[] = str_repeat('-', 70);
    $out[] = "-- HOST: $label   (connection `$conn`)";
    $out[] = '-- ' . count($rows) . ' row(s) restored across ' . count($profileIds) . ' employee profile(s)';
    $out[] = str_repeat('-', 70);
    $out[] = '';
    $out[] = 'START TRANSACTION;';
    $out[] = '';
    $out[] = '-- 1. Clear whatever the migration left behind on the touched menus.';
    $out[] = 'DELETE FROM tblgroupwise_rights_g2g';
    $out[] = ' WHERE profile_id IN (' . implode(',', $profileIds) . ')';
    $out[] = '   AND menu_id    IN (' . implode(',', $touched) . ');';
    $out[] = '';

    if ($rows === []) {
        $out[] = '-- 2. Nothing to restore: this host held no rows on these menus.';
    } else {
        $out[] = '-- 2. Put back exactly what was there, flags included.';
        $values = [];
        foreach ($rows as $r) {
            $values[] = sprintf(
                '  (%d, %d, %d, %d, %d, %d, %s)',
                (int) $r['menu_id'],
                (int) $r['profile_id'],
                (int) $r['can_view'],
                (int) $r['can_add'],
                (int) $r['can_edit'],
                (int) $r['can_delete'],
                $r['sub_institute_id'] === null ? 'NULL' : (int) $r['sub_institute_id']
            );
        }
        $out[] = 'INSERT INTO tblgroupwise_rights_g2g';
        $out[] = '  (menu_id, profile_id, can_view, can_add, can_edit, can_delete, sub_institute_id)';
        $out[] = 'VALUES';
        $out[] = implode(",\n", $values) . ';';
    }

    $out[] = '';
    $out[] = '-- 3. Confirm before committing. Expected: ' . count($rows);
    $out[] = 'SELECT COUNT(*) AS restored FROM tblgroupwise_rights_g2g';
    $out[] = ' WHERE profile_id IN (' . implode(',', $profileIds) . ')';
    $out[] = '   AND menu_id    IN (' . implode(',', $touched) . ');';
    $out[] = '';
    $out[] = 'COMMIT;';
    $out[] = '';
}

$dest = __DIR__ . '/../_reversals/REVERSAL-2026-09-21-employee-leave-menu.sql';
file_put_contents($dest, implode("\n", $out) . "\n");
echo "written: $dest\n";
foreach ($hosts as $conn => $label) {
    if (!isset($before[$conn])) { continue; }
    $n = count(array_filter($before[$conn]['rights'], fn ($r) => in_array((int) $r['menu_id'], $touched, true)));
    printf("  %-6s %d row(s) to restore\n", $conn, $n);
}
