<?php

namespace App\Domain\AI\Chat;

use App\Domain\AI\Modules\ModuleRollUp;
use App\Domain\AI\Reports\ModuleDataSourceCatalog;
use App\Domain\AI\Reports\ReportBuilder;
use App\Services\Ai\AiRequestScope;
use Illuminate\Support\Facades\DB;

/**
 * Reports from the chat assistant, for the module the chat is open in.
 *
 * NOTHING HERE IS GENERATED BY A MODEL
 *
 * The assistant only picks, from what the module really has, which published report
 * template and which read-only data source answer the user's message, and then asks
 * `ReportBuilder` (the same code `POST /workspace/report` runs) to build and save it.
 * The figures are the tenant's own rows. When nothing matches, or the match has no rows,
 * the answer is `null` plus a reason - never an invented report.
 *
 * MATCHING IS DETERMINISTIC
 *
 * Message words are scored against each source's label, name and description and the
 * names of the published report templates bound to it. Nothing here lists modules,
 * sources or templates: they come from `ModuleDataSourceCatalog`, `ai_templates` and
 * `ModuleRollUp`, so a new source or template is matchable without a code change.
 *
 * SEND / PRINT
 *
 * `can_send` is true when ReportDeliveryService can send for the caller (admin, MailGate open
 * for the tenant, deliveries table present). Sending is POST /chat/reports/{id}/send.
 * Print is the saved report page's own print (`url_path`).
 */
class ChatReportService
{
    /** Words that say "make me a report" rather than which one. */
    private const STOPWORDS = [
        'the', 'and', 'for', 'with', 'from', 'that', 'this', 'about', 'please', 'can', 'could', 'would',
        'you', 'your', 'our', 'give', 'show', 'get', 'make', 'build', 'create', 'generate', 'prepare',
        'report', 'reports', 'summary', 'list', 'all', 'any', 'need', 'want', 'new', 'one', 'run',
        'full', 'latest', 'current', 'data', 'details', 'detail', 'view', 'print', 'send',
    ];

    public function __construct(
        private readonly ModuleDataSourceCatalog $sources,
        private readonly ReportBuilder $builder,
        private readonly ModuleRollUp $rollUp,
        private readonly ReportDeliveryService $delivery,
    ) {
    }

    /**
     * Build and save the report the message asks for.
     *
     * @return array{id:int,title:string,module_key:string,template_id:int|null,data_source:string,row_count:int,url_path:string,generated_at:string,can_send:bool}|null
     *         Null when nothing matched or the match had no rows; see `attempt()` for the reason.
     */
    public function generate(AiRequestScope $scope, string $moduleKey, string $message): ?array
    {
        return $this->attempt($scope, $moduleKey, $message)['report'];
    }

    /**
     * Report types the module really has: its published report templates and its data sources.
     *
     * @return array<int, array{label:string,prompt:string,data_source:string,template_id:int|null,template_name:string|null,module_key:string,description:string}>
     *         When `$message` is given, only the types matching it (best first).
     */
    public function suggest(AiRequestScope $scope, string $moduleKey, ?string $message = null): array
    {
        $candidates = $this->candidates($scope, $moduleKey);

        if ($message !== null && trim($message) !== '') {
            $scored = [];
            foreach ($candidates as $candidate) {
                $score = $this->score($candidate, $this->tokens($message));
                if ($score > 0) {
                    $scored[] = [$score, $candidate];
                }
            }
            usort($scored, fn ($a, $b) => $b[0] <=> $a[0]);
            $candidates = array_map(fn ($pair) => $pair[1], $scored);
        }

        return array_map(fn (array $c) => [
            'label' => $c['label'],
            // Phrased from the label so it scores against its own source when sent back.
            'prompt' => 'Generate the ' . $c['label'] . ' report',
            'data_source' => $c['source'],
            'template_id' => $c['template'] === null ? null : (int) $c['template']->id,
            'template_name' => $c['template'] === null ? null : (string) $c['template']->name,
            'module_key' => $c['module_key'],
            'description' => $c['description'],
        ], $candidates);
    }

    /**
     * `generate()` with the reason it declined, for callers that tell the user why.
     *
     * @return array{report: array<string,mixed>|null, reason: string|null, matched: string|null}
     */
    public function attempt(AiRequestScope $scope, string $moduleKey, string $message): array
    {
        $module = DB::table('ai_modules')
            ->where('module_key', $moduleKey)
            ->where('status', 1)
            ->where(fn ($q) => $q->where('sub_institute_id', $scope->selectedInstituteId)->orWhereNull('sub_institute_id'))
            ->orderByRaw('sub_institute_id IS NULL ASC')
            ->first(['module_key', 'label']);

        if ($module === null) {
            return $this->declined('There is no AI module called "' . $moduleKey . '", so no report can be built for it.');
        }

        // The saved-report page and its API are administrator-only; a report a user cannot
        // open would be a dead link.
        if (! $scope->isAdmin && ! $scope->isPlatformOwner) {
            return $this->declined('Reports are available to administrators.');
        }

        $candidates = $this->candidates($scope, $moduleKey);

        if ($candidates === []) {
            return $this->declined($module->label . ' has no report template or read-only data source to build a report from.');
        }

        $tokens = $this->tokens($message);
        $best = null;
        $bestScore = 0;

        foreach ($candidates as $candidate) {
            $score = $this->score($candidate, $tokens);
            if ($score > $bestScore) {
                $best = $candidate;
                $bestScore = $score;
            }
        }

        if ($best === null) {
            return $this->declined(
                'Nothing in ' . $module->label . ' matches that request. Available reports: '
                . implode(', ', array_map(fn ($c) => $c['label'], $candidates)) . '.'
            );
        }

        $layout = $best['template'];
        $arguments = $this->declaredOnly($best['source'], $this->decode($layout->data_arguments ?? null));

        $built = $this->builder->build(
            $scope,
            $best['module_key'],
            (string) ($this->moduleLabel($best['module_key'], $scope) ?? $module->label),
            $best['source'],
            $layout,
            $arguments,
            $message
        );

        if ($built['id'] === null) {
            return $this->declined('"' . $best['label'] . '" matched, but it has no records for this organisation, so no report was made.', $best['label']);
        }

        return [
            'report' => [
                'id' => $built['id'],
                'title' => $built['title'],
                'module_key' => $best['module_key'],
                'template_id' => $layout === null ? null : (int) $layout->id,
                'data_source' => $best['source'],
                'row_count' => $built['row_count'],
                'url_path' => '/ai/reports/' . $built['id'],
                'generated_at' => $built['generated_at'],
                'can_send' => $this->delivery->canSend($scope),
            ],
            'reason' => null,
            'matched' => $best['label'],
        ];
    }

    // ------------------------------------------------------------------ internals

    /**
     * One candidate per source the module can read, with the best template bound to it.
     *
     * @return array<int, array{label:string,description:string,source:string,module_key:string,template:object|null,templates:array<int,object>,haystack:array<string,int>}>
     */
    private function candidates(AiRequestScope $scope, string $moduleKey): array
    {
        $institute = $scope->selectedInstituteId;
        $sources = $this->sources->forModule($moduleKey);

        if ($sources === []) {
            return [];
        }

        $templates = DB::table('ai_templates')
            ->whereIn('module_key', $this->rollUp->keysFor($moduleKey))
            ->where('kind', 'report')
            ->where('status', 'published')
            ->whereNotNull('data_source')
            ->where(fn ($q) => $q->where('sub_institute_id', $institute)->orWhereNull('sub_institute_id'))
            // The organisation's own layout wins over the platform's, then the newest.
            ->orderByRaw('sub_institute_id IS NULL ASC')
            ->orderByDesc('updated_at')
            ->get();

        $out = [];

        foreach ($sources as $source) {
            $bound = $templates->where('data_source', $source['name'])->values()->all();
            $words = [];

            foreach ($this->tokens($source['label'] . ' ' . str_replace(['.', '_'], ' ', $source['name'])) as $w) {
                $words[$w] = 2;
            }
            foreach ($this->tokens($source['description']) as $w) {
                $words[$w] = $words[$w] ?? 1;
            }
            foreach ($bound as $t) {
                foreach ($this->tokens($t->name . ' ' . ($t->description ?? '')) as $w) {
                    $words[$w] = max($words[$w] ?? 0, 2);
                }
            }

            $template = $bound[0] ?? null;

            $out[] = [
                'label' => $template !== null
                    ? (string) preg_replace('/\s*\(example\)\s*$/i', '', (string) $template->name)
                    : (string) $source['label'],
                'description' => (string) $source['description'],
                'source' => (string) $source['name'],
                // A layout is filed under the screen that owns it; a source-only report under the source's.
                'module_key' => $template !== null ? (string) $template->module_key : (string) $source['module'],
                'template' => $template,
                'templates' => $bound,
                'haystack' => $words,
            ];
        }

        return $out;
    }

    /** @param array<int,string> $tokens */
    private function score(array $candidate, array $tokens): int
    {
        $score = 0;

        foreach (array_unique($tokens) as $token) {
            $score += $candidate['haystack'][$token] ?? 0;
        }

        return $score;
    }

    /** @return array<int,string> */
    private function tokens(string $text): array
    {
        preg_match_all('/[a-z0-9]+/', mb_strtolower($text), $m);
        $out = [];

        foreach ($m[0] as $word) {
            if (strlen($word) < 3) {
                continue;
            }
            // Crude plural fold, so "enrolments" meets "enrolment".
            if (strlen($word) > 4 && str_ends_with($word, 's') && ! str_ends_with($word, 'ss')) {
                $word = substr($word, 0, -1);
            }
            if (in_array($word, self::STOPWORDS, true)) {
                continue;
            }
            $out[] = $word;
        }

        return $out;
    }

    private function declaredOnly(string $source, array $given): array
    {
        $declared = array_column($this->sources->describe($source)['arguments'] ?? [], 'key');

        return array_intersect_key($given, array_flip($declared));
    }

    private function moduleLabel(string $moduleKey, AiRequestScope $scope): ?string
    {
        return DB::table('ai_modules')
            ->where('module_key', $moduleKey)
            ->where(fn ($q) => $q->where('sub_institute_id', $scope->selectedInstituteId)->orWhereNull('sub_institute_id'))
            ->orderByRaw('sub_institute_id IS NULL ASC')
            ->value('label');
    }

    private function decode(mixed $value): array
    {
        $decoded = is_string($value) ? json_decode($value, true) : $value;

        return is_array($decoded) ? $decoded : [];
    }

    /** @return array{report:null,reason:string,matched:string|null} */
    private function declined(string $reason, ?string $matched = null): array
    {
        return ['report' => null, 'reason' => $reason, 'matched' => $matched];
    }
}
