<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Neutralise the one fabricated event in the store, before reactors are driven.
 *
 * ── WHAT IT IS ──────────────────────────────────────────────────────────────
 *
 * `g2g_event` id 100, type `certification.expiring`, on BOTH databases with the
 * same id and the same timestamp to the millisecond:
 *
 *   id=100  tenant=1  entity=2968  occurred=2026-08-11 11:46:55.075  actor=NULL
 *   payload={"certification_id":2968}
 *
 * An event generated by running code would not land on two separate databases
 * with an identical id and sub-second timestamp. It was copied, not emitted.
 *
 * And its subject is not expiring. Certification 2968 is `status='valid'` with
 * `expiry_date = 2027-08-05` — eleven months out on both sides.
 *
 * ── WHY IT MATTERS NOW ──────────────────────────────────────────────────────
 *
 * Until this release nothing drove the reactors, so the row was inert. `events:react`
 * makes it live: NotificationDispatcher would tell user 2 that a certification
 * valid for another eleven months is about to lapse, and RemediationRecommender
 * would suggest remedial courses for it. A false alarm to a real person is the
 * worst possible first output of a notification system that has never sent
 * anything.
 *
 * ── WHY SUPPRESSED AND NOT DELETED ──────────────────────────────────────────
 *
 * An event store is append-only; that is most of what makes it trustworthy. A
 * migration that deletes from it teaches the next person that history is
 * editable, which costs more than this row is worth.
 *
 * The ledger already expresses exactly this. `skipped` means "this consumer
 * looked and had nothing to do" — a distinct fact from `done` and from never
 * having looked — and `catchUp()` treats any ledger row as handled. So a skipped
 * row per reactor consumer suppresses the event, records WHY in `last_error`, and
 * leaves the store intact and auditable. Reversing it is one delete, which is
 * what down() does.
 *
 * Written for the two consumers that handle this type today. If a third is added
 * later it will pick the event up — deliberately: the suppression is a statement
 * about two known consumers, not a permanent property of the row.
 *
 * RUN ON BOTH DATABASES:
 *   php artisan migrate --path=database/migrations/2026_08_31_220000_suppress_fabricated_certification_event.php
 *   php artisan migrate --database=live --path=database/migrations/2026_08_31_220000_suppress_fabricated_certification_event.php
 */
return new class extends Migration
{
    /** The consumers whose HANDLES/NOTIFIES include `certification.expiring`. */
    private const CONSUMERS = ['notification_dispatcher', 'remediation_recommender'];

    private const REASON = 'fabricated test event: subject certification is valid until 2027-08-05, not expiring';

    public function up(): void
    {
        if (! $this->tableExists('g2g_event') || ! $this->tableExists('g2g_event_delivery')) {
            return;
        }

        /*
         * Matched on the SHAPE, not on id 100. If the row is absent — a fresh
         * database, or somebody removed it — this is a no-op rather than an
         * insert that invents a ledger entry for an event that does not exist.
         */
        $events = DB::table('g2g_event')
            ->where('type', 'certification.expiring')
            ->whereNull('actor_id')
            ->where('occurred_at', '<', '2026-08-12')
            ->pluck('id');

        foreach ($events as $eventId) {
            foreach (self::CONSUMERS as $consumer) {
                $exists = DB::table('g2g_event_delivery')
                    ->where('event_id', (int) $eventId)
                    ->where('consumer', $consumer)
                    ->exists();

                // Never overwrite a real delivery. If a reactor has already
                // processed this, the fact of that is more valuable than the
                // suppression.
                if ($exists) {
                    continue;
                }

                DB::table('g2g_event_delivery')->insert([
                    'event_id'     => (int) $eventId,
                    'consumer'     => $consumer,
                    'status'       => 'skipped',
                    'attempts'     => 0,
                    'last_error'   => self::REASON,
                    'completed_at' => null,
                ]);
            }
        }
    }

    public function down(): void
    {
        if (! $this->tableExists('g2g_event_delivery')) {
            return;
        }

        // Only the rows this migration wrote — identified by the reason string,
        // so a genuine skip recorded later by a live run is left alone.
        DB::table('g2g_event_delivery')
            ->whereIn('consumer', self::CONSUMERS)
            ->where('status', 'skipped')
            ->where('last_error', self::REASON)
            ->delete();
    }

    /** Schema::hasTable() throws on live (MariaDB 10.1.48); read the catalogue directly. */
    private function tableExists(string $table): bool
    {
        $rows = DB::select(
            'SELECT COUNT(*) AS c FROM information_schema.TABLES
              WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?',
            [$table]
        );

        return (int) ($rows[0]->c ?? 0) > 0;
    }
};
