<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * AI-GENERATED CAPABILITY ASSESSMENT — three tables.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY NEW TABLES RATHER THAN s_competency_assessments
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * s_competency_assessments is the CYCLE/CAMPAIGN record: one row per person per
 * assessor per framework, carrying an overall percentage score. It has no
 * question, no answer and no item. Putting generated questions in it would
 * repeat the mistake this feature already contains four times over - a column
 * declared for a purpose it cannot serve.
 *
 * These three are also DELIBERATELY NOT WIRED TO CYCLES. A cycle cannot yet say
 * what it is scoped to (`type` is NULL in all 4, framework_id in 0 of 4), and
 * building on it would make this feature inherit that. A test is scoped to a JOB
 * ROLE, which is a thing that exists and is populated.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * THE GUARD IS STRUCTURAL: NO ITEM, NO QUESTION
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Every question carries `kasba_item_id` and it is NOT NULL. A question cannot
 * exist without a real capability item behind it.
 *
 * That is the whole defence against the failure mode an LLM makes possible: an
 * AI generates PLAUSIBLE output by design, so a test about competencies nobody
 * authored would look exactly like a test about competencies somebody did. Every
 * check in this system turns on the difference between absent and
 * present-looking. Here the difference is enforced by a NOT NULL column rather
 * than by a rule someone must remember.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * NOTHING IS HARDCODED
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `format` is a varchar, not an enum: mcq and short_answer are what is being
 * built, and an enum would need a migration to add a third. `options` is JSON so
 * an MCQ may have any number of choices. `model` records WHICH LLM produced a
 * test, because a test generated by one model is not evidence about another.
 */
return new class extends Migration
{
    public function up(): void
    {
        // ── the test: one per job role, generated once, taken by many ──────────
        if (!Schema::hasTable('competency_assessment_test')) {
            Schema::create('competency_assessment_test', function (Blueprint $table) {
                $table->id();
                $table->unsignedBigInteger('sub_institute_id');
                $table->unsignedBigInteger('jobrole_id');
                $table->string('title', 191);
                $table->text('instructions')->nullable();
                // WHICH MODEL PRODUCED THIS. Not decoration: a test generated by
                // one model is not evidence about another, and if a model is
                // changed the tests it produced must remain identifiable.
                $table->string('model', 100)->nullable();
                $table->string('status', 30)->default('draft');
                $table->unsignedBigInteger('generated_by');
                $table->timestamp('published_at')->nullable();
                $table->timestamps();
                $table->softDeletes();

                $table->index(['sub_institute_id', 'jobrole_id'], 'cat_tenant_jobrole_index');
                $table->index(['sub_institute_id', 'status'], 'cat_tenant_status_index');
            });
        }

        // ── the questions ─────────────────────────────────────────────────────
        if (!Schema::hasTable('competency_assessment_question')) {
            Schema::create('competency_assessment_question', function (Blueprint $table) {
                $table->id();
                $table->unsignedBigInteger('sub_institute_id');
                $table->unsignedBigInteger('test_id');
                // NOT NULL ON PURPOSE. See the guard above: no item, no question.
                $table->unsignedBigInteger('kasba_item_id');
                $table->string('format', 30);             // mcq | short_answer
                $table->text('question_text');
                $table->json('options')->nullable();       // MCQ choices; null for short_answer
                $table->string('correct_option', 50)->nullable();
                $table->text('model_answer')->nullable();  // short_answer reference
                $table->unsignedSmallInteger('max_score')->default(1);
                $table->unsignedSmallInteger('sort_order')->default(0);
                $table->timestamps();

                $table->index(['test_id', 'sort_order'], 'caq_test_order_index');
                $table->index('kasba_item_id', 'caq_item_index');
                $table->index('sub_institute_id', 'caq_tenant_index');
            });
        }

        // ── the answers ───────────────────────────────────────────────────────
        if (!Schema::hasTable('competency_assessment_response')) {
            Schema::create('competency_assessment_response', function (Blueprint $table) {
                $table->id();
                $table->unsignedBigInteger('sub_institute_id');
                $table->unsignedBigInteger('test_id');
                $table->unsignedBigInteger('question_id');
                $table->unsignedBigInteger('user_id');
                $table->text('answer_text')->nullable();
                $table->string('selected_option', 50)->nullable();
                // NULLABLE ON PURPOSE. UNANSWERED IS NOT ZERO - an unanswered
                // question is unanswered, not a score of nothing, and a
                // short_answer awaiting review is unscored rather than failed.
                $table->decimal('score', 5, 2)->nullable();
                $table->string('scored_by', 30)->nullable();   // auto | manual
                $table->timestamp('answered_at')->nullable();
                $table->timestamps();

                // One answer per person per question. THIS key is safe to assert
                // because it is being created with the table - unlike the one
                // proposed on s_competency_assessments, which would have been
                // imposed on data that already refused it.
                $table->unique(['question_id', 'user_id'], 'car_question_user_unique');
                $table->index(['sub_institute_id', 'user_id'], 'car_tenant_user_index');
                $table->index(['test_id', 'user_id'], 'car_test_user_index');
            });
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('competency_assessment_response');
        Schema::dropIfExists('competency_assessment_question');
        Schema::dropIfExists('competency_assessment_test');
    }
};
