-- REVERSAL - 2026-09-21 - employee HRIT menu rights (F-209)
--
-- Reverses database/migrations/2026_09_21_120000_give_employees_the_leave_menu.php
-- GENERATED by Docs/hrit-audit/_evidence/gen-reversal-nav.php from
-- Docs/hrit-audit/_evidence/before-nav-employee.json, captured before the
-- migration ran. Do not hand-edit: regenerate.
--
-- Prefer:  php artisan migrate:rollback --step=1
--          php artisan migrate:rollback --database=live --step=1
-- This file is the exact-fidelity restore for when that is not available,
-- or when the prior state must be proven row by row.

----------------------------------------------------------------------
-- HOST: 202.47.117.220 (web.triz.co.in)   (connection `mysql`)
-- 19 row(s) restored across 11 employee profile(s)
----------------------------------------------------------------------

START TRANSACTION;

-- 1. Clear whatever the migration left behind on the touched menus.
DELETE FROM tblgroupwise_rights_g2g
 WHERE profile_id IN (3,6,9,12,15,17,20,26,30,32,174)
   AND menu_id    IN (94,103,95,105,106,107,108,109,110,140,307,308,310,311,101,162,163,164,102,104,165,166,167);

-- 2. Put back exactly what was there, flags included.
INSERT INTO tblgroupwise_rights_g2g
  (menu_id, profile_id, can_view, can_add, can_edit, can_delete, sub_institute_id)
VALUES
  (94, 3, 1, 0, 0, 0, 1),
  (95, 3, 1, 0, 0, 0, 1),
  (101, 3, 1, 0, 0, 0, 1),
  (102, 3, 1, 0, 0, 0, 1),
  (103, 3, 1, 0, 0, 0, 1),
  (104, 3, 1, 0, 0, 0, 1),
  (105, 3, 1, 0, 0, 0, 1),
  (106, 3, 1, 0, 0, 0, 1),
  (107, 3, 1, 0, 0, 0, 1),
  (108, 3, 1, 0, 0, 0, 1),
  (109, 3, 1, 0, 0, 0, 1),
  (110, 3, 1, 0, 0, 0, 1),
  (140, 3, 1, 0, 0, 0, 1),
  (162, 3, 1, 0, 0, 0, 1),
  (163, 3, 1, 0, 0, 0, 1),
  (164, 3, 1, 0, 0, 0, 1),
  (165, 3, 1, 0, 0, 0, 1),
  (166, 3, 1, 0, 0, 0, 1),
  (167, 3, 1, 0, 0, 0, 1);

-- 3. Confirm before committing. Expected: 19
SELECT COUNT(*) AS restored FROM tblgroupwise_rights_g2g
 WHERE profile_id IN (3,6,9,12,15,17,20,26,30,32,174)
   AND menu_id    IN (94,103,95,105,106,107,108,109,110,140,307,308,310,311,101,162,163,164,102,104,165,166,167);

COMMIT;

----------------------------------------------------------------------
-- HOST: 128.199.17.97 (lms.triz.co.in)   (connection `live`)
-- 26 row(s) restored across 2 employee profile(s)
----------------------------------------------------------------------

START TRANSACTION;

-- 1. Clear whatever the migration left behind on the touched menus.
DELETE FROM tblgroupwise_rights_g2g
 WHERE profile_id IN (3,17)
   AND menu_id    IN (94,103,95,105,106,107,108,109,110,140,307,308,310,311,101,162,163,164,102,104,165,166,167);

-- 2. Put back exactly what was there, flags included.
INSERT INTO tblgroupwise_rights_g2g
  (menu_id, profile_id, can_view, can_add, can_edit, can_delete, sub_institute_id)
VALUES
  (94, 3, 1, 0, 0, 0, NULL),
  (95, 3, 1, 0, 0, 0, NULL),
  (101, 3, 1, 0, 0, 0, NULL),
  (102, 3, 1, 0, 0, 0, NULL),
  (103, 3, 1, 0, 0, 0, NULL),
  (104, 3, 1, 0, 0, 0, NULL),
  (105, 3, 1, 0, 0, 0, NULL),
  (106, 3, 1, 0, 0, 0, NULL),
  (108, 3, 1, 0, 0, 0, NULL),
  (109, 3, 1, 0, 0, 0, NULL),
  (110, 3, 1, 0, 0, 0, NULL),
  (140, 3, 1, 0, 0, 0, NULL),
  (165, 3, 1, 0, 0, 0, NULL),
  (94, 17, 1, 0, 0, 0, 6),
  (95, 17, 1, 0, 0, 0, 6),
  (101, 17, 1, 0, 0, 0, 6),
  (102, 17, 1, 0, 0, 0, 6),
  (103, 17, 1, 0, 0, 0, 6),
  (104, 17, 1, 0, 0, 0, 6),
  (105, 17, 1, 0, 0, 0, 6),
  (106, 17, 1, 0, 0, 0, 6),
  (108, 17, 1, 0, 0, 0, 6),
  (109, 17, 1, 0, 0, 0, 6),
  (110, 17, 1, 0, 0, 0, 6),
  (140, 17, 1, 0, 0, 0, 6),
  (165, 17, 1, 0, 0, 0, 6);

-- 3. Confirm before committing. Expected: 26
SELECT COUNT(*) AS restored FROM tblgroupwise_rights_g2g
 WHERE profile_id IN (3,17)
   AND menu_id    IN (94,103,95,105,106,107,108,109,110,140,307,308,310,311,101,162,163,164,102,104,165,166,167);

COMMIT;

