<?php

namespace App\Domain\AI\Configuration;

use App\Domain\AI\Support\SchemaCache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * The model a module's AI Stack → Models choice selects for a generator that speaks
 * DeepSeek directly — with a safety check in front of it.
 *
 * WHY THIS EXISTS (audit CRA-027)
 *
 * Every module's Models tab saves a row in `ai_module_model_bindings`, but the
 * generators behind `lms_content_ai`, `eso_intelligence` and `assessment_ai` called
 * `DeepSeekService` with the global `config('deepseek.model')` and never read it.
 * The save worked; nothing used it.
 *
 * WHY IT IS NOT JUST A RESOLVER CALL
 *
 * `ai_models` is admin-editable and every module's picker offers all of it, so
 * trusting the row as-is lets an admin choose a model these generators were never
 * tuned for (config/deepseek.php records models that spend the whole output budget
 * and return nothing parseable). So a binding is honoured only when
 *
 *   1. its provider is `deepseek` — these generators speak the DeepSeek protocol and
 *      cannot send another provider's model id, and
 *   2. its model is on `config('deepseek.allowed_models')`.
 *
 * Anything else returns null, which means "use `config('deepseek.model')`" — exactly
 * what the generator did before bindings were read, so an unbound or unsafe binding
 * changes nothing.
 *
 * NOTHING HERE READS REQUEST INPUT. The tenant comes from the caller's already
 * authenticated context.
 */
class ModuleDeepSeekModel
{
    public function __construct(
        private readonly ModuleModelBindings $bindings,
        private readonly SchemaCache $schema,
    ) {
    }

    /** Capabilities whose generators call DeepSeekService directly, and so read this. */
    public const CAPABILITIES = ['lms_content_ai', 'eso_intelligence', 'assessment_ai'];

    public static function supports(string $capability): bool
    {
        return in_array($capability, self::CAPABILITIES, true);
    }

    /** Whether a model id may be sent by a binding-driven call. */
    public function isAllowed(string $model): bool
    {
        return in_array(trim($model), (array) config('deepseek.allowed_models', []), true);
    }

    /**
     * Why a provider/model pair cannot be honoured, or null when it can.
     * Used both to refuse a bad save and to explain an ignored row.
     */
    public function refusal(string $provider, ?string $model): ?string
    {
        if ($provider !== 'deepseek') {
            return 'This capability is generated by DeepSeek directly, so only a DeepSeek model can be chosen for it.';
        }

        $model = trim((string) $model);

        if ($model === '') {
            return null; // No model named: the configured default is used.
        }

        if (! $this->isAllowed($model)) {
            return 'That model has not been verified for this generator. Allowed: '
                . implode(', ', (array) config('deepseek.allowed_models', [])) . '.';
        }

        return null;
    }

    /**
     * The model to send for one capability, or null for the configured default.
     *
     * @param  array<int, string>  $preferredModules  `ai_modules` keys to try first, in order
     *                                                (the screen the work happens on).
     */
    public function modelFor(string $capability, int|string|null $subInstituteId, array $preferredModules = []): ?string
    {
        if (! self::supports($capability)) {
            return null;
        }

        try {
            foreach ($this->candidateModules($capability, $preferredModules) as $module) {
                $binding = $this->bindings->find($module, $capability, $subInstituteId);

                if ($binding === null) {
                    continue;
                }

                $reason = $this->refusal((string) $binding->provider, $binding->model ?? null);

                if ($reason !== null) {
                    Log::warning('Module model binding ignored; using the configured default', [
                        'capability' => $capability,
                        'module' => $module,
                        'provider' => $binding->provider,
                        'model' => $binding->model ?? null,
                        'reason' => $reason,
                    ]);

                    continue;
                }

                $model = trim((string) ($binding->model ?? ''));

                return $model === '' ? null : $model;
            }
        } catch (Throwable $e) {
            // A binding lookup must never take a generator down.
            Log::warning('Module model binding lookup failed; using the configured default', [
                'capability' => $capability,
                'error' => $e->getMessage(),
            ]);
        }

        return null;
    }

    /**
     * A model id supplied by a caller, kept only if it is on the allowlist.
     * `AiCourseController` has always accepted one from the request body.
     */
    public function sanitise(?string $requested): ?string
    {
        $requested = trim((string) $requested);

        return $requested !== '' && $this->isAllowed($requested) ? $requested : null;
    }

    /**
     * The `ai_modules` keys that list this capability, preferred ones first.
     *
     * @return array<int, string>
     */
    private function candidateModules(string $capability, array $preferred): array
    {
        $found = [];

        if ($this->schema->hasTable('ai_modules') && $this->schema->hasColumn('ai_modules', 'registry_keys')) {
            $rows = DB::table('ai_modules')->where('status', 1)->whereNotNull('registry_keys')->get(['module_key', 'registry_keys']);

            foreach ($rows as $row) {
                $keys = json_decode((string) $row->registry_keys, true);

                if (is_array($keys) && in_array($capability, $keys, true)) {
                    $found[] = (string) $row->module_key;
                }
            }
        }

        return array_values(array_unique(array_merge($preferred, $found)));
    }
}
